version: '3.7'

services:
  db: 
    container_name: "tutorial_db"
    build: 
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "secret"
    volumes:
    - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: "tutorial_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
     - .:/app/
networks:
  default:
volumes:
  mysql_data: