name: Ci

on:
  pull_request:




jobs:

  list_runners:
    runs-on: ubuntu-24.04
    steps:
      - name: List runners
        run: |
          echo "Available runners:"
          gh api repos/OWNER/REPO/actions/runners --paginate \ --jq '.runners[] | {id, name, status, labels}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 


  setup:
    runs-on: pldm
    strategy:
      matrix:
        dummy: [dummy1, dummy2]
    outputs:
      runner_name: ${{ runner.name }}
    steps:
      - name: Print runner name
        run: echo Set up runner ${{ runner.name }}, with dummy ${{ matrix.dummy }}


  test:
    runs-on: ${{ needs.setup.outputs.runner_name }}
    needs: setup
    strategy:
      matrix:
        dummy: [dummy1, dummy2]
    steps:
      - name: Print runner name
        run: echo "Running on ${{ runner.name }}, with dummy ${{ matrix.dummy }}"
