name: Ci

on:
  pull_request:


jobs:
  setup:
    runs-on: pldm
    outputs:
      runner_name: ${{ runner.name }}
    steps:
      - name: Print runner name
        run: echo "Running on ${{ runner.name }}"


  test:
    runs-on: ${{ needs.setup.outputs.runner_name }}
    needs: setup
    steps:
      - name: Print runner name
        run: echo "Running on ${{ runner.name }}"