name: Ci

on:
  workflow_call:
    inputs:
      runner_name:
        required: true
        type: string
      manifest:
        required: true
        type: string
      project:
        required: true
        type: string


jobs:

  setup:
    runs-on: ${{inputs.runner_name }}
    strategy:
      matrix:
        dummy: [dummy1, dummy2]
    outputs:
      runner_name: ${{ runner.name }}
    steps:
      - name: Print runner name
        run: echo Set up runner ${{ runner.name }}, with dummy ${{ matrix.dummy }}


  test:
    runs-on: ${{inputs.runner_name }}
    needs: setup
    strategy:
      matrix:
        dummy: [dummy1, dummy2]
    steps:
      - name: Print runner name
        run: echo "Running on ${{ runner.name }}, with dummy ${{ matrix.dummy }}"
