name: Regression test

on:
  pull_request:



permissions:
 actions: read
 contents: read
 


jobs:
  pldm_free_runners:
    runs-on: ubuntu-latest
    outputs:
      runners: ${{ steps.list_runners.outputs.runners }}
      data: ${{ steps.list_runners.outputs.data }}
      max-parallel: ${{ steps.list_runners.outputs.max-parallel }}
    steps:
      - name: List runners
        id: list_runners
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          echo "Available runners:"
          runners=$(curl -s -H "Authorization: token ${{ secrets.LETS_GO_TOKEN }}" \
           -H "Accept: application/vnd.github+json" \
           https://api.github.com/repos/ezratameno/lets_go/actions/runners \
           | jq -c '[.runners[] | select(.status == "online") | select(.labels[].name == "pldm") | .name]')

          echo "Available runners: $runners"

          echo runners=$runners >> $GITHUB_OUTPUT

          
          data=$(echo '[ { "manifest": "manifest1", "project": "project1","runner": "Ezra-ta-LPT" },{ "manifest": "manifest2", "project": "project2","runner": "Ezra-ta-LPT" },{ "manifest": "manifest3", "project": "project3","runner": "Ezra-ta-LPT" },{ "manifest": "manifest4", "project": "project4","runner": "Ezra-ta-LPT" }]') 
          echo $data
          echo data=$data >> $GITHUB_OUTPUT

          num_runners=$(cat results.json | jq .num_runners)
          echo num runners: $num_runners
          echo max-parallel=2 >> $GITHUB_OUTPUT

      
  
  run_ci:
    needs: [pldm_free_runners]
    uses: ./.github/workflows/ci.yaml
    with:
      runner_name: ${{(matrix.data).runner }}
      manifest: ${{(matrix.data).manifest }}
      project: ${{(matrix.data).project }}
    strategy:
      max-parallel: ${{ needs.pldm_free_runners.outputs.max-parallel }}
      fail-fast: false
      matrix:
        data: ${{fromJSON(needs.pldm_free_runners.outputs.data) }}
